{% set name = "G2Aero" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com//NREL/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b9edb1f9fcc1403a44b34decc063a4e7716cebb9815669f52b68584dc8c37894

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pyyaml
    - scipy
    - setuptools

test:
  imports:
    - g2aero
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/NREL/G2Aero
  summary: 'G2Aero: Separable shape tensors for aerodynamic applications'
  description: |
    G2Aero is a flexible and practical tool for design and deformation of 
    2D airfoils and 3D blades using data-driven approaches. G2Aero 
    utilizes the geometry of matrix manifolds—specifically the Grassmannian
    to build a novel framework for representing physics-based separable 
    deformations of shapes. G2Aero offers the flexibility to generate 
    perturbations in a customizable way over any portion of the blade. 
    The G2Aero framework utilizes data-driven methods based on a curated 
    database of physically relevant airfoils.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - olgadoronina
    - zgrey
